### PR TITLE
add Proximity sensor

### PR DESCRIPTION
**Pull request by zxcpoiu**
add Proximity sensor support

return event data:

```
data = {
    isNear: (boolean) true/false,
    distance: (douable) 
}
```

### CODE REVIEW

**Comment by kprimice** [comment]
The "distance" takes only 0 or 5 on my phone. Have you tested it?
It is working but if "distance" takes only 2 values we could keep "isNear" only.

**Comment by zxcpoiu** [comment]
Actually, I'm not sure why the value keep the same...
But I have once saw a strange value:

```
I/ReactNativeJS(23704): stop() button pressed
I/ReactNativeJS(23704): start() button pressed
I/ReactNativeJS(23704): 'Proximity: ', { isNear: false, distance: 9 }
I/ReactNativeJS(23704): 'Proximity: ', { isNear: false, distance: 38654705664 }
I/ReactNativeJS(23704): 'Proximity: ', { isNear: false, distance: 9 }
I/ReactNativeJS(23704): start() button pressed
I/ReactNativeJS(23704): 'Proximity: ', { isNear: true, distance: 0 }
```

anyway, you are right, I think it would be enough to keep `isNear` only, I will update the PR.

**Comment by zxcpoiu** [comment]
PR updated

**Comment by zxcpoiu** [comment]
thanks!

below is just a note for future debug:

from: [Using the Proximity Sensor](http://developer.android.com/guide/topics/sensors/sensors_position.html#sensors-pos-prox)

> Note: Some proximity sensors return binary values that represent "near" or "far." In this case, the sensor usually reports its maximum range value in the far state and a lesser value in the near state. Typically, the far value is a value > 5 cm, but this can vary from sensor to sensor. You can determine a sensor's maximum range by using the getMaximumRange() method.

**Pull request merged**
